[project]
name = "jobSalaryPrediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "fastapi",
    "uvicorn",
    "pydantic",
    "scikit-learn",
    "torch",
    "mlflow",
    "dagshub",
    "dvc",
    "ensure",
    "python-box",
    "pyYAML",
    "notebook",
    "gdown",
    "optuna>=5.0.0",
    "xgboost>=3.4.1",
]
