artifact_dir: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  data_source: "https://drive.google.com/uc?export=download&id=1SmXNvzqRwLkeyHwKVhbFSQ7BHp72d8F9"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion


data_validation:
  root_dir: artifact/data_validation
  data_path: artifact/data_ingestion/job_salary_prediction_dataset.csv
  status_file: artifact/data_validation/status.txt